### ISSUE TITLE
Add new --resolvfile and --resolvfile-poll options

### ISSUE THREAD

**Issue by h0tbird** [janeczku/go-dnsmasq#2]
Thank you for `go-dnsmasq` I won't be able to run any `musl-libc` distro without it :-)
I don't run it inside every Alpine container, instead, I run it on the Docker host (mesos node) with the `--default-resolver` flag.  

I wish I could watch a file for `nameserver` records and update accordingly. Something like this:

```
--resolvfile /etc/mesos-dns-servers.conf
--resolvfile-poll 60
```

Where `/etc/mesos-dns-servers.conf` contains dynamically populated `nameserver` records.

Thank you again!

**Comment by h0tbird** [comment]
Oh! This changes everything: http://wiki.musl-libc.org/wiki/Roadmap#musl_1.1.13
"Search domain support in resolver" :-)

**Comment by janeczku** [comment]
> Where /etc/mesos-dns-servers.conf contains dynamically populated nameserver records.

@h0tbird Hi, could you explain what you mean by "nameserver records"?

> Oh! This changes everything: http://wiki.musl-libc.org/wiki/Roadmap#musl_1.1.13

Thanks for the info - This is indeed good news!

**Comment by h0tbird** [comment]
Yes. I mean the `/etc/mesos-dns-servers.conf` will look something like this:

```
nameserver 10.128.0.83
nameserver 10.128.0.95
nameserver 10.128.0.101
nameserver 10.128.0.2
```

The content of this file is dynamic based on DNS servers availability.

**Comment by janeczku** [comment]
Closing this for now. Dynamic nameservers are an edge case and implementing support for that would be too intrusive.
