### ISSUE TITLE
Caching not working

### ISSUE THREAD

**Issue by setiseta** [janeczku/go-dnsmasq#26]
Hello,

I'm trying to use your docker for dns caching.
But i cant figure out which settings to do, to get it work.
I tested without any environment variables, and with DNSMASQ_RCACHE.

In both cases a dig gets always forwarded to the nameserver i set for the docker with DNSMASQ_SERVERS
(checked with a tcpdump)

Can you explain the settings to just use caching functionality?

Thx for help.

PS: the setting DNSMASQ_DEFAULT is not usefull for the docker, or it needs to be changed, cause it inserts a nameserver 0.0.0.0 to the resolv.conf of the docker.

**Comment by janeczku** [comment]
HI @setiseta, i assume you are using the image from Docker Hub? This one ships with the minimal version of the application which comes without caching functionality. See https://github.com/janeczku/go-dnsmasq#run-from-the-command-line. You should probably create your own image using the full version binary.

**Comment by cknowles** [comment]
Would it be acceptable to add a column to the options table stating which ones work for minimal/full? I was thinking of submitting that so it was more obvious which options work where.
