### ISSUE TITLE
Usage of --stubmasks

### ISSUE THREAD

**Issue by affixalex** [janeczku/go-dnsmasq#3]
I'm starting up go-dnsmasq like this. When it takes the consul-agent branch, I get the correct results from `dig @127.0.0.1 -p 8600` but this isn't working without explicitly specifying the Consul DNS server.

Any ideas?

```
#!/bin/sh

AGENT=`getent hosts consul-agent`
if [ -z "$AGENT" ]; then
        echo "Consul Agent detected. Using Consul DNS..."
        go-dnsmasq --default-resolver \
                   --search-domains service.consul \
                   --append-search-domains \
                   --hostsfile=/etc/hosts \
                   --stubzones service.consul/127.0.0.1:8600 \
                   --nameservers 8.8.8.8,8.8.4.4
else
        echo "No Consul Agent detected!"
        go-dnsmasq --default-resolver \
                   --append-search-domains \
                   --hostsfile=/etc/hosts \
                   --nameservers 8.8.8.8,8.8.4.4

fi;
```

**Comment by janeczku** [comment]
>  I get the correct results from dig @127.0.0.1 -p 8600

I don't quite get it. go-dnsmasq is obviously not running on port 8600. So why do you think it to be it's fault that you don't get the correct results from this `dig` command?

Could you elaborate on what behavior you expect in the `else` block? 
And rather tell me what queries you are sending to go-dnsmasq and what the expected and actual result is. Also, whats in your resolv.conf before you launch go-dnsmasq?

**Comment by affixalex** [comment]
Ah, sorry, consul runs a DNS server at 127.0.0.1:8600 and I'd like DNS requests to 127.0.0.1:53 (go-dnsmasq) for the .consul domain to be forwarded to the Consul DNS server at 127.0.0.1:8600 - sorry for the confusion!

```
# dig @127.0.0.1 -p 8600 app.service.consul SRV
;; ANSWER SECTION:
app.service.consul.     0       IN      SRV     1 1 4000 718f10c5c39f.node.dc1.consul.
# dig @127.0.0.1 app.service.consul SRV
;; AUTHORITY SECTION:
natwky.rr.com.          1799    IN      SOA     dns1.rr.com. dnsadmin.rr.com. 2016012023 21600 3600 604800 3600
```

**Comment by janeczku** [comment]
And the second dig command relates to which situation in the if/else statement?

**Comment by janeczku** [comment]
So this:

```
        go-dnsmasq --default-resolver \
                   --search-domains service.consul \
                   --append-search-domains \
                   --hostsfile=/etc/hosts \
                   --stubzones service.consul/127.0.0.1:8600 \
                   --nameservers 8.8.8.8,8.8.4.4

```

results in this:

```
# dig @127.0.0.1 app.service.consul SRV
;; AUTHORITY SECTION:
natwky.rr.com.          1799    IN      SOA     dns1.rr.com. dnsadmin.rr.com. 2016012023 21600 3600 604800 3600

```

?

**Comment by affixalex** [comment]
The second dig command occurs in both branches, whereas I want go-dnsmasq to forward the .consul lookups to 127.0.0.1:8600 in the "Consul Agent detected. Using Consul DNS..." branch. So when it takes the first branch, I should get the `app.service.consul.     0       IN      SRV     1 1 4000 718f10c5c39f.node.dc1.consul.` response on 127.0.0.1:53 from go-dnsmasq (forwarded from 127.0.0.1:8600). 

I think there is something wrong with `--stubzones service.consul/127.0.0.1:8600` - the docs say it takes an FQDN so presumably `--stubzones .consul/127.0.0.1:8600` won't work either (I think I tried it and it didn't, but maybe another error elsewhere).

Also, thanks so much for the quick response! I really appreciate it.

**Comment by janeczku** [comment]
> the docs say it takes an FQDN

So the stubzone expects a domain name with at least two labels, e.g. `service.consul` but not `consul`. 
The trailing dot is optional, `service.consul` and `service.consul.` both work, but `.consul` is not a FQDN.

I am having trouble reproducing this. With your command line args all queries ending in `service.consul` get forwarded to Consul and rest is forwarded to Google DNS as expected.

```
        go-dnsmasq --default-resolver \
                   --search-domains service.consul \
                   --append-search-domains \
                   --hostsfile=/etc/hosts \
                   --stubzones service.consul/127.0.0.1:8600 \
                   --nameservers 8.8.8.8,8.8.4.4
```

I suspect something else is going on:

> ```
> dig @127.0.0.1 app.service.consul SRV
> ;; AUTHORITY SECTION:
> natwky.rr.com.          1799    IN      SOA     dns1.rr.com. dnsadmin.rr.com. 2016012023 21600 3600 604800 3600
> ```

Where does that record come from? Certainly not from 8.8.8.8!

> $ dig app.service.consul SRV @8.8.8.8

```
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 26520
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;app.service.consul.        IN  SRV

;; AUTHORITY SECTION:
.           1799    IN  SOA a.root-servers.net. nstld.verisign-grs.com. 2016021101 1800 900 604800 86400

;; WHEN: Fri Feb 12 04:40:56 2016
;; MSG SIZE  rcvd: 111
```

**Comment by affixalex** [comment]
The actual code is at https://github.com/hypoalex/docker-alpine/blob/master/alpine-base/root/etc/services.d/resolver/run (not a plug, these aren't close to ready for real use at all) and it's possible to test this with a simple `docker run -it hypoalex/alpine-base /bin/sh` (to take the no consul branch) or `docker run -it hypoalex/alpine-consul /bin/sh`to take the consul forwarding branch in the run script. I'll tag the alpine-consul-nodejs image and upload it later with details on how to reproduce this.

I get somewhat strange behavior when I use for example `docker run --dns 123.123.123.123`  - I'm not totally sure that I understand the relationship between the Docker command line, /etc/resolv.conf, and go-dnsmasq. The idea is that individual Node servers should be able to simply do DNS requests like normal and speak to each other.

Thanks so much for your time!

I think this is a pretty compelling use case for go-dnsmasq so if nothing else it might be useful to anyone reading (even once musl gets dns search support). I'll update this and close it when I figure it out, but obviously feel free to have a look!

**Comment by janeczku** [comment]
> not sure that I understand the relationship between the Docker command line, /etc/resolv.conf, and go-dnsmasq.

Well, go-dnsmasq will use whatever nameservers are defined in resolv.conf as upstream servers to forward queries to. That is unless the query matches a stub-zone OR you override the list of upstream nameservers with the `--nameservers` flag.

**Comment by janeczku** [comment]
An alternative approach for Consul while not using stub-zones flag would be to:
1. Enable recursors option in consul and set it to 8.8.8.8, 8.8.4.4 see https://www.consul.io/docs/agent/options.html#recursors
2. For go-dnsmasq use the flag `--nameservers 127.0.0.1:8600`

**Comment by janeczku** [comment]
Seems to be resolved.
