### ISSUE TITLE
Comments out multiple times in resolv.conf

### ISSUE THREAD

**Issue by matthewvalimaki** [janeczku/go-dnsmasq#7]
When using `go-dnsmasq --default-resolver --append-search-domains --hostsfile=/etc/hosts -n 127.0.0.1:8600` as a service and restarting it seems to cause additive commenting in `/etc/resolv.conf`:

```
# # #nameserver 8.8.8.8
# # # # # # nameserver 8.8.4.4
```

All I need to do is to restart and `#` is added. Reason why the lines look different is because I manually modified the file to enable the 1st nameserver.

I recommend adding a check before `#` is added.

**Comment by janeczku** [comment]
Thanks for you report! :smile:
