### ISSUE TITLE
Support IPv6 nameservers

### ISSUE THREAD

**Issue by Luzifer** [janeczku/go-dnsmasq#9]
> As a user being in a network running native IPv6 I prefer to use IPv6 nameserver addresses not to use those constructs mapping IPv4 through IPv6.
## Observed behaviour

When trying to start `go-dnsmasq` using `go-dnsmasq [...] -n 2001:4860:4860::8888,2001:4860:4860::8844,8.8.8.8,8.8.4.4 [...]` I get this error message:

> FATA[0000] This nameserver is invalid: too many colons in address 2001:4860:4860::8888

When trying to start `go-dnsmasq` using `go-dnsmasq [...] -n [2001:4860:4860::8888],[2001:4860:4860::8844],8.8.8.8,8.8.4.4 [...]` I get this error message:

> FATA[0000] This nameserver is invalid: missing port in address [2001:4860:4860::8888]
## Expected behaviour

When starting `go-dnsmasq` using `go-dnsmasq [...] -n 2001:4860:4860::8888,2001:4860:4860::8844,8.8.8.8,8.8.4.4 [...]` it is not crashing and trying to resolve names using that IPv6 nameserver.

**Comment by janeczku** [comment]
Literal IPv6 addresses must be have host part enclosed by brackets (RFC).
Looks like the current code also requires the port to be explicitly set for IPv6 addresses. Could you try this:
`go-dnsmasq -n "[2001:4860:4860::8888]:53"`

**Comment by Luzifer** [comment]
Indeed: When including the port it works:

``` bash
DNSMASQ_OPTS+=" -n [2001:4860:4860::8888]:53,[2001:4860:4860::8844]:53,8.8.8.8,8.8.4.4"
```

Closing this issue as it's just wrong usage.
